---
title: "Data Import"
author: "Amitra Hoq"
output: github_document
date: "2026-09-15"
---

#This file is for doing data import

```{r}

library(tidyverse)
library(readxl)
library(haven)
```



## Import our first data set 

```{r}
litters_df =
  read.csv("data/FAS_litters.csv", 
            na= c("","NA",".")
        )

litters_df = janitor:: clean_names(litters_df)
litters_df

```

## import second data set 

```{r}

pups_df = 
  read_csv("data/FAS_pups.csv", 
           skip = 3,
            na= c("","NA",".")
          )
pups_df = janitor:: clean_names(pups_df)
pups_df

```


## Head or tail
``` {r}
head(litters_df, 20)

tail(pups_df,5)
```

## skimming 

```{r}

skimr::skim(pups_df)

```

## Oh excel..

Jenny Bryan made `readxl` to solve our probrlems
```{r}
mlb_df=
  read_excel("data/mlb11.xlsx")

mlb_df
``` 

## Load LoTR


```{r}
fotr_df= 
  read_excel("data/LotR_Words.xlsx",
          range="B3:D6"   
      )

fotr_df
```
```{r}
tt_df= 
  read_excel("data/LotR_Words.xlsx",
          range="F3:H6"   
      )

tt_df
```

```{r}
rotk_df= 
  read_excel("data/LotR_Words.xlsx",
          range="J3:L6"   
      )

rotk_df
```

## Import SAS file 

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
pulse_df

```